config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  # root to: 'pages#index'
  root to: redirect('/users/sign_in')
  resources :users, only: %i[show update destroy]

  namespace :dashboard do
    get '/', to: 'welcome#index'
    resources :events, only: %i[show index] do
      collection do
        get 'filter_events', as: :filter
      end
      resources :comments
      resources :volunteer_hours
    end
  end
  
  # ------------ ADMIN ROUTES ------------

  namespace :admin do
    get '/', to: 'events#index'
    resources :events do
      resources :comments, only: :index
    end
    resources :regions do
      resources :users, only: :index
    end
    resources :users
    resources :volunteer_hours do
      post 'update_hour', as: :update_hour
      post 'update_status', as: :update_status
      collection do
        get 'filter_volunteer_hours', as: :filter
        get 'unvolunteered_events', as: :unvolunteered_events
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :volunteer_hours, dependent: :destroy
  has_many :users, through: :volunteer_hours
  belongs_to :region

  has_one_attached :event_image

  validates :name, presence: true
  validates :venue, presence: true
  validates :max_limit, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  scope :active, -> { where(active: true) }
  scope :archived, -> { where(active: false) }
  scope :search, -> (search) { where('events.name ILIKE ?', "%#{search}%") }

  def event_ended?
    Time.zone.now > end_time
  end

  # submit hours
  def deadline_passed?(event_volunteer_hour = nil)
    return false if event_volunteer_hour.present?
    event_ended? && Time.zone.now > (end_time + 5.months)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :load_event, except: %i[index create new]
  def index
    params[:active] ||= 'true'
    if params[:active].eql?('true')
      events = Event.active
      @events_title = 'Active Events'
    else
      events = Event.archived
      @events_title = 'Archived Events'
    end
    
    @pagy, @events = pagy(
      events.includes(:region)
            .search(params[:search])
            .order("#{sort_column} #{sort_direction}, events.name")
            .distinct
    )
  end

  def new
    @event = Event.new
  end

  def show
    @volunteer_events = Event.includes(:users)
                             .includes(:volunteer_hours)
                             .where(id: @event.id)
                             .order(sort_by_multiple_columns)
                             .references(:users)
                             .references(:volunteer_hours)
    @event_volunteers = @volunteer_events.first.users.where(volunteer_hours: {status: VolunteerHour::ACCEPTED})
    @total_hours_volunteered = @event.volunteer_hours.where(status: VolunteerHour::ACCEPTED).pluck(:time_worked).reduce(:+) || 0
  end

  def create
    Event.create!(event_params)
    redirect_to admin_events_path
  end

  def update
    @event.update(event_params)
    redirect_to admin_events_path
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit!
  end

  def load_event
    @event = Event.find(params[:id])
  end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < ApplicationController
  before_action :authenticate_user!
  include Pagy::Backend

  def index
    @page_title = 'All Events'
    @pagy, @events = pagy(Event.active.order(start_time: :desc))
  end

  def filter_events
    region_id = params[:region_id]
    events = Event.active
    if region_id.present?
      @page_title = "Events in #{Region.find(region_id).name}"
      @pagy, @events = pagy(events.where(region_id: region_id).order(start_time: :desc))
    elsif params[:past_events]
      @page_title = 'Past Events'
      @pagy, @events = pagy(events.where('end_time < ?', Time.now).order(start_time: :desc))
    elsif params[:upcoming_events]
      @page_title = 'Upcoming Events'
      @pagy, @events = pagy(events.where('end_time >= ?', Time.now).order(:start_time))
    elsif params[:my_events]
      @page_title = 'My Events'
      user_event_ids = current_user.events.pluck(:id)
      @pagy, @events = pagy(events.where(id: user_event_ids).order(start_time: :desc))
    else
      @page_title = 'All Events'
      @pagy, @events = pagy(events.order(start_time: :desc))
    end

    respond_to do |format|
      format.html { render action: :index }
      format.js {}
    end
  end

  def show
    @comment = Comment.new
    @volunteer_hour = VolunteerHour.new
    @event = Event.find(params[:id])
    @event_volunteer_hour = @event.volunteer_hours.where(user_id: current_user.id).last
    @page_title = "#{@event.name} in #{@event.region.name}"
  end

  private

  def pagy_get_vars(collection, vars)
    item_name = if params[:past_events].present?
      'activerecord.models.past_events'
    elsif params[:upcoming_events].present?
      'activerecord.models.upcoming_events'
    elsif params[:region_id].present?
      regional_events = Region.find_by(id: params[:region_id])&.events
      regional_events&.count > 1 ? 'activerecord.models.events' : "activerecord.models.#{Event.model_name.i18n_key}"
    else
      "activerecord.models.events"
    end

    {
      count: collection.count,
      page: params['page'],
      items: vars[:items] || 12,
      i18n_key: item_name
    }
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @regions = Region.all
    @events_filter = EventsFilter.new(events_filter_params)
    if @events_filter.region.present?
      @events = Event.where(region_id: @events_filter.region)
    else
      @events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_volunteer_hour = current_user.volunteer_hours.first
    @comment = Comment.new
    @volunteer_hour = VolunteerHour.new
  end

  private

  def events_filter_params
    params.fetch(:events_filter, {}).permit(
      :region
    )
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def hours_volunteered( volunteer_id, event_id )
    VolunteerHour.find_by(user_id: volunteer_id, event_id: event_id)&.time_worked
  end
  
  def pending_volunteer_hours_review?( event )
    event.volunteer_hours.exists?(status: VolunteerHour::REQUESTED)
  end
end

app/helpers/events_helper.rb
module EventsHelper
	def event_image_or_default_url(event)
		if event.event_image.attached?
			url_for(event.event_image)
		else
			image_url('events/event-placeholder.jpg')
		end
	end
end

app/views/admin/events/_form.html.erb
<div class="grid-x">
	<div class="cell large-6 medium-6">
		<%= simple_form_for [:admin, @event] do |f| %>
			<%= f.input :active, as: :boolean %>
			<%= f.input :name %>
			<%= f.input :description, input_html: {rows: '4'} %>
			<%= f.input :max_limit %>
			<%= f.input :region_id, as: :select, collection: Region.all, selected: @event.region.present? ? @event.region.id : nil %>
			<%= f.input :venue %>
			<%= f.label 'Start time' %>
			<%= f.input :start_time, as: :datetime, ampm: true, label: false, default: Date.today %>
			<%= f.label 'End time' %>
			<%= f.input :end_time, as: :datetime, ampm: true, label: false, default: Date.today %>
			<% if @event.event_image.attached? %>
				<%= image_tag @event.event_image, class: 'thumbnail form-thumbnail' %>
				<%= f.label 'Update image' %>
			<% else %>
				<%= f.label 'Upload event image' %>
			<% end %>
			<%= f.file_field :event_image %>
			<%= f.submit 'Save', class: 'button' %>
			<%= link_to 'Cancel', admin_events_path, class: 'button', style: 'margin-left:0.5rem;' %>
		<% end %>
	</div>
</div>

app/views/admin/events/_search_form.html.erb
<%= form_tag admin_events_path, method: :get, id: 'search-events' do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<div class="grid-x grid-margin-x">
		<div class="cell large-5 medium-5 small-8">
			<%= text_field_tag :search, params[:search], placeholder: 'Search events by Name' %>
		</div>
		<div class="cell auto">
			<%= submit_tag 'Search', name: nil, class: 'button search-button' %>
		</div>
	</div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="admin-page admin-events-page" id="edit-event">
	<h1 class="text-center">Edit Event</h1>
	<%= render partial: 'form' %>
</div>

app/views/admin/events/index.html.erb
<div class="admin-page admin-events-page">
  <h1 class="text-center">
    <%= @events_title %>
  </h1>
  <ul class="tabs-ul">
    <%= link_to admin_events_path(active: true), class: ('active' if params[:active] == 'true') do %>
      <li>Active</li>
    <% end %>
    <%= link_to admin_events_path(active: false), class: ('active' if params[:active] == 'false') do %>
      <li>Archived</li>
    <% end %>
  </ul>
  <%= link_to 'New Event', new_admin_event_path, class: 'button' if params[:active] == 'true' %>
  <% if @events.any? %>
    <%= render partial: 'search_form' %>
    <div class="table-scroll">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>
              <%= sortable('events.name', 'Name') %>
            </th>
            <th>Image</th>
            <th class="show-for-medium">Description</th>
            <th>
              <%= sortable('start_time', 'Start') %>
            </th>
            <th class="show-for-medium">
              <%= sortable('end_time', 'End') %>
            </th>
            <th>
              <%= sortable('regions.name', 'Region') %>
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td>
                <%= event.id %>
              </td>
              <td>
                <%= link_to event.name, admin_event_path(event) %>
              </td>
              <td>
                <%= image_tag event_image_or_default_url(event), class: 'thumbnail' %>
              </td>
              <td class="show-for-medium">
                <%= truncate(event.description) %>
              </td>
              <td>
                <%= event.start_time&.strftime("%m/%d/%y") %>
              </td>
              <td class="show-for-medium">
                <%= event.end_time&.strftime("%m/%d/%y") %>
              </td>
              <td>
                <%= event.region.name %>
              </td>
              <td>
                <%= link_to edit_admin_event_path(event), class: 'edit-action' do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
                <%= link_to admin_event_path(event), class: 'delete-action', data: { confirm: "Are you sure you would like to delete the #{event.name} event?", method: :delete } do %>
                  <i class="fa fa-trash"></i>
                <% end %>
                <%= link_to admin_event_comments_path(event), class: 'edit-action' do %>
                  <i class="fa fa-comments-o"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <div class="pagination-wrapper admin">
    <div class="pagination-info">
      <%= pagy_info(@pagy).html_safe %>
    </div>
    <%= pagy_foundation_nav(@pagy).html_safe if @pagy.pages > 1 %>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="admin-page admin-events-page" id="new-event">
	<h1 class="text-center">New Event</h1>
	<%= render partial: 'form' %>
</div>

app/views/admin/events/show.html.erb
<div class="admin-page admin-events-page">
  <div class="cell">
    <%= link_to admin_events_path do %>
      <i class="fa fa-chevron-left"></i>
      Back to Events
    <% end %>
    <br/>
    <br/>
  </div>
  <h1 class="text-center">
    <%= @event.name %>
  </h1>
  <% if @total_hours_volunteered > 0 %>
    <% if pending_volunteer_hours_review?( @event ) %>
      <p class="description text-center error-message">
        Volunteer hours are pending your review for this event.
      </p>
    <% end %>
    <p class="description">
      Total hours volunteered:
      <span>
        <%= @total_hours_volunteered %>
      </span>
    </p>
    <div class="table-scroll">
      <table>
        <thead>
          <tr>
            <th>
              <%= sortable('users.first_name, users.last_name','Volunteer') %>
            </th>
            <th>
              <%= sortable('volunteer_hours.time_worked', 'Hours Volunteered') %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @event_volunteers.each do |volunteer| %>
            <tr>
              <td>
                <%= volunteer.name %>
              </td>
              <td>
                <%= hours_volunteered( volunteer.id, @event.id ) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% elsif pending_volunteer_hours_review?( @event ) %>
    <p class="description text-center error-message">
      Volunteer hours are pending your review for this event.
    </p>
  <% else %>
    <p class="description text-center">
      No volunteer hours submitted for this event, yet.
    </p>
  <% end %>
</div>