config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  # root to: 'pages#index'
  root to: redirect('/users/sign_in')
  resources :users, only: %i[show update destroy]

  namespace :dashboard do
    get '/', to: 'welcome#index'
    resources :events, only: %i[show index] do
      collection do
        get 'filter_events', as: :filter
      end
      resources :comments
      resources :volunteer_hours
    end
  end
  
  # ------------ ADMIN ROUTES ------------

  namespace :admin do
    get '/', to: 'events#index'
    resources :events do
      resources :comments, only: :index
    end
    resources :regions do
      resources :users, only: :index
    end
    resources :users
    resources :volunteer_hours do
      post 'update_hour', as: :update_hour
      post 'update_status', as: :update_status
      collection do
        get 'filter_volunteer_hours', as: :filter
        get 'unvolunteered_events', as: :unvolunteered_events
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :volunteer_hours, dependent: :destroy
  has_many :users, through: :volunteer_hours
  belongs_to :region

  has_one_attached :event_image

  validates :name, presence: true
  validates :venue, presence: true
  validates :max_limit, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  scope :active, -> { where(active: true) }
  scope :archived, -> { where(active: false) }
  scope :search, -> (search) { where('events.name ILIKE ?', "%#{search}%") }

  def event_ended?
    Time.zone.now > end_time
  end

  # submit hours
  def deadline_passed?(event_volunteer_hour = nil)
    return false if event_volunteer_hour.present?
    event_ended? && Time.zone.now > (end_time + 5.months)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :load_event, except: %i[index create new]
  def index
    params[:active] ||= 'true'
    if params[:active].eql?('true')
      events = Event.active
      @events_title = 'Active Events'
    else
      events = Event.archived
      @events_title = 'Archived Events'
    end
    
    @pagy, @events = pagy(
      events.includes(:region)
            .search(params[:search])
            .order("#{sort_column} #{sort_direction}, events.name")
            .distinct
    )
  end

  def new
    @event = Event.new
  end

  def show
    @volunteer_events = Event.includes(:users)
                             .includes(:volunteer_hours)
                             .where(id: @event.id)
                             .order(sort_by_multiple_columns)
                             .references(:users)
                             .references(:volunteer_hours)
    @event_volunteers = @volunteer_events.first.users.where(volunteer_hours: {status: VolunteerHour::ACCEPTED})
    @total_hours_volunteered = @event.volunteer_hours.where(status: VolunteerHour::ACCEPTED).pluck(:time_worked).reduce(:+) || 0
  end

  def create
    Event.create!(event_params)
    redirect_to admin_events_path
  end

  def update
    @event.update(event_params)
    redirect_to admin_events_path
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit!
  end

  def load_event
    @event = Event.find(params[:id])
  end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < ApplicationController
  before_action :authenticate_user!
  include Pagy::Backend

  def index
    @page_title = 'All Events'
    @pagy, @events = pagy(Event.active.order(start_time: :desc))
  end

  def filter_events
    region_id = params[:region_id]
    events = Event.active
    if region_id.present?
      @page_title = "Events in #{Region.find(region_id).name}"
      @pagy, @events = pagy(events.where(region_id: region_id).order(start_time: :desc))
    elsif params[:past_events]
      @page_title = 'Past Events'
      @pagy, @events = pagy(events.where('end_time < ?', Time.now).order(start_time: :desc))
    elsif params[:upcoming_events]
      @page_title = 'Upcoming Events'
      @pagy, @events = pagy(events.where('end_time >= ?', Time.now).order(:start_time))
    elsif params[:my_events]
      @page_title = 'My Events'
      user_event_ids = current_user.events.pluck(:id)
      @pagy, @events = pagy(events.where(id: user_event_ids).order(start_time: :desc))
    else
      @page_title = 'All Events'
      @pagy, @events = pagy(events.order(start_time: :desc))
    end

    respond_to do |format|
      format.html { render action: :index }
      format.js {}
    end
  end

  def show
    @comment = Comment.new
    @volunteer_hour = VolunteerHour.new
    @event = Event.find(params[:id])
    @event_volunteer_hour = @event.volunteer_hours.where(user_id: current_user.id).last
    @page_title = "#{@event.name} in #{@event.region.name}"
  end

  private

  def pagy_get_vars(collection, vars)
    item_name = if params[:past_events].present?
      'activerecord.models.past_events'
    elsif params[:upcoming_events].present?
      'activerecord.models.upcoming_events'
    elsif params[:region_id].present?
      regional_events = Region.find_by(id: params[:region_id])&.events
      regional_events&.count > 1 ? 'activerecord.models.events' : "activerecord.models.#{Event.model_name.i18n_key}"
    else
      "activerecord.models.events"
    end

    {
      count: collection.count,
      page: params['page'],
      items: vars[:items] || 12,
      i18n_key: item_name
    }
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @regions = Region.all
    @events_filter = EventsFilter.new(events_filter_params)
    if @events_filter.region.present?
      @events = Event.where(region_id: @events_filter.region)
    else
      @events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_volunteer_hour = current_user.volunteer_hours.first
    @comment = Comment.new
    @volunteer_hour = VolunteerHour.new
  end

  private

  def events_filter_params
    params.fetch(:events_filter, {}).permit(
      :region
    )
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def hours_volunteered( volunteer_id, event_id )
    VolunteerHour.find_by(user_id: volunteer_id, event_id: event_id)&.time_worked
  end
  
  def pending_volunteer_hours_review?( event )
    event.volunteer_hours.exists?(status: VolunteerHour::REQUESTED)
  end
end

app/helpers/events_helper.rb
module EventsHelper
	def event_image_or_default_url(event)
		if event.event_image.attached?
			url_for(event.event_image)
		else
			image_url('events/event-placeholder.jpg')
		end
	end
end

app/views/events/index.haml
.grid-x.events
	.cell.large-6.medium-6
		= simple_form_for(@events_filter, url: events_path, method: :get) do |f|
			= f.input :region, as: :select, collection: @regions, prompt: 'Select a Region', selected: (params[:events_filter].present? ? params[:events_filter][:region] : nil), input_html: {"data-remote" => true, onchange: "this.form.submit();"}
	- if params[:events_filter].present?
		.cell
			= link_to 'See all Events', events_path
			%br
			%br
		.cell
			%h5 Events by Region
			- unless @events.empty?
				%p.helper-text
					Click on an event to submit the hours volunteered.
	- else
		.cell
			%h5 All Events
			- unless @events.empty?
				%p.helper-text
					Click on an event to submit the hours volunteered.
	
	- if @events.empty? && params[:events_filter].present?
		%p.helper-text
			= "No events found in #{Region.find(params[:events_filter][:region]).name}."
	- else
		.cell.large-6.medium-6
			%table
				%thead
					%tr
						%th Name
						%th Region
				%tbody
					- @events.each do |event|
						%tr
							%td
								= link_to event.name, event_path(event)
							%td
								= event.region.name

app/views/events/show.haml
.grid-x.events
  .cell
    %i.fa.fa-chevron-left{style:'color:#7CA5C2;margin-right:0.5rem;'}
    = link_to 'Back to Events', events_path
    %br
    %br
  .cell
    %h2
      = @event.name
  .cell
    %p.helper-text
      = @event.region.name
  .cell.large-8.medium-8
    - if @event_volunteer_hour.present?
      %table
        %thead
          %tr
            %th
              Time worked
            %th
              Submitted at
            %th
              Status
        %tbody
          %tr
            %td
              = @event_volunteer_hour.time_worked
              hrs
            %td
              = @event_volunteer_hour.created_at
            %td
              - if @event_volunteer_hour.status.eql?('accepted')
                Approved
                %i.fa.fa-check{style: 'color: green'}
              - elsif @event_volunteer_hour.status.eql?('rejected')
                Rejected
              - else
                Pending Review

    - else
      .cell
        = simple_form_for [ @event, @volunteer_hour ] do |f|
          = f.input :time_worked, placeholder: '# of hours worked'
          = f.submit 'Submit', class: 'button'    
  .cell
    %h4
      Comments
  .cell.large-8.medium-8
    - @event.comments.each do |comment|
      .cell
        %span
          = "#{comment.user.first_name} #{comment.user.last_name}"
      .cell
        = comment.text
      / .cell
      /   -# comment.image.each do |i|
      /     %img{src: url_for(i), width: '200'}
  .cell.large-8.medium-8
    = simple_form_for [ @event, @comment ] do |f|
      = f.input :text, :input_html => {rows: 4}, label: 'Comment ( optional )', class: 'helper-text'
      =# f.file_field :image, multiple: true
      = f.submit 'Submit', class: 'button'