config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  # root to: 'pages#index'
  root to: redirect('/users/sign_in')
  resources :users, only: %i[show update destroy]

  namespace :dashboard do
    get '/', to: 'welcome#index'
    resources :events, only: %i[show index] do
      collection do
        get 'filter_events', as: :filter
      end
      resources :comments
      resources :volunteer_hours
    end
  end
  
  # ------------ ADMIN ROUTES ------------

  namespace :admin do
    get '/', to: 'events#index'
    resources :events do
      resources :comments, only: :index
    end
    resources :regions do
      resources :users, only: :index
    end
    resources :users
    resources :volunteer_hours do
      post 'update_hour', as: :update_hour
      post 'update_status', as: :update_status
      collection do
        get 'filter_volunteer_hours', as: :filter
        get 'unvolunteered_events', as: :unvolunteered_events
      end
    end
  end
end

app/views/layouts/navigation/user_view/_desktop_view.html.erb
<ul class="dropdown menu">
  <% if user_signed_in? %>
    <li id="logo">
      <%= link_to dashboard_path, id: 'logo-link' do %>
        <%= image_tag 'jakara-logo.png', id: 'jakara-logo' %>
      <% end %>
    </li>
    <% if is_admin? %>
      <li class="nav-item">
        <%= link_to 'Admin', admin_events_path %>
      </li>
    <% end %>
    <li class="nav-item">
      <%= link_to 'Events', dashboard_events_path %>
      <section class="<%= ('pointer' if params[:controller].split('/').last&.eql?('events')) %>"></section>
    </li>
  <% else %>
    <li id="logo">
      <%= link_to root_path, id: 'logo-link' do %>
        <%= image_tag 'jakara-logo.png', id: 'jakara-logo' %>
      <% end %>
    </li>
  <% end %>
</ul>
<ul class="dropdown menu">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link', id: 'logout' %>
    </li>
  <% else %>
    <li class="nav-item" id="sign-up-button">
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
    <li class="nav-item" id="sign-in-button">
      <%= link_to 'Sign in', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/navigation/user_view/_mobile_view.html.erb
<% if user_signed_in? %>
  <ul class="dropdown menu">
    <li>
      <a href="javascript:void(0)" id="burger-menu">
        <span class="burger-icon"></span>
      </a>
    </li>
    <li id="logo">
      <%= link_to dashboard_path, id: 'logo-link' do %>
        <%= image_tag 'jakara-logo.png', id: 'jakara-logo' %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link', id: 'logout' %>
    </li>
  </ul>
<% else %>
  <div id="signed-out-nav">
    <div id="logo">
      <%= link_to root_path, id: 'logo-link' do %>
        <%= image_tag 'jakara-logo.png', id: 'jakara-logo' %>
      <% end %>
    </div>
    <div id="authenticate-user-wrapper">
      <div class="nav-item" id="sign-up-button">
        <%= link_to 'Sign up', new_user_registration_path %>
      </div>
      <div class="nav-item" id="sign-in-button">
        <%= link_to 'Sign in', new_user_session_path %>
      </div>
    </div>
  </div>
<% end %>
<div id="mobile-nav-container">
  <%= render partial: 'layouts/navigation/user_view/side_nav' %>
</div>
<script>

  $('#burger-menu').on('click', function(e){
    e.preventDefault();
    this.classList.toggle('is-active');
    if ($('#burger-menu').hasClass('is-active')) {
      $('#mobile-nav-container').animate({left: 0});
    } else {
      $('#mobile-nav-container').animate({left: -250});
    }
  })

</script>

app/views/layouts/navigation/user_view/_side_nav.html.erb
<ul class="side-nav" role="navigation">
  <% if is_admin? %>
    <li class="admin-head-li" role="navheading">Admin Panel</li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Events', admin_events_path %>
    </li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Volunteers', admin_users_path %>
    </li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Volunteer Hours', admin_volunteer_hours_path %>
    </li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Regions', admin_regions_path %>
    </li>
    <li class="admin-head-li" role="navheading">User View</li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Dashboard', dashboard_path   %>
    </li>
    <li class="admin-li" role="navitem">
      <%= link_to 'Events', dashboard_events_path %>
    </li>
  <% else %>
    <li role="navitem">
      <%= link_to 'Events', dashboard_events_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li role="navitem">
      <%= link_to 'My Profile', user_path(current_user) %>
    </li>
    <li role="navitem">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/layouts/navigation/user_view/_user_nav.html.erb
<div class="navigation top-bar">
  <div class="top-bar-left">
    <div class="page-container">
      <div class="nav-page-wrapper">
        <div class="<%= ('logged-out-view' unless user_signed_in?) %> navigation-wrapper user-view show-for-medium">
          <%= render partial: 'layouts/navigation/user_view/desktop_view' %>
        </div>
        <div class="navigation-wrapper show-for-small-only">
          <%= render partial: 'layouts/navigation/user_view/mobile_view' %>
        </div>
      </div>
    </div>
  </div>
</div>