config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  # root to: 'pages#index'
  root to: redirect('/users/sign_in')
  resources :users, only: %i[show update destroy]

  namespace :dashboard do
    get '/', to: 'welcome#index'
    resources :events, only: %i[show index] do
      collection do
        get 'filter_events', as: :filter
      end
      resources :comments
      resources :volunteer_hours
    end
  end
  
  # ------------ ADMIN ROUTES ------------

  namespace :admin do
    get '/', to: 'events#index'
    resources :events do
      resources :comments, only: :index
    end
    resources :regions do
      resources :users, only: :index
    end
    resources :users
    resources :volunteer_hours do
      post 'update_hour', as: :update_hour
      post 'update_status', as: :update_status
      collection do
        get 'filter_volunteer_hours', as: :filter
        get 'unvolunteered_events', as: :unvolunteered_events
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :birth_month, :birth_day, :birth_year
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable

  has_many :volunteer_hours, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :events, through: :volunteer_hours

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :phone, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  validates :parent_email, presence: true
  validates :parent_first_name, presence: true
  validates :parent_last_name, presence: true
  validates :parent_phone, presence: true
  validates :school_year, presence: true
  validates :email, presence: true, uniqueness: true
  validates :parent_email, presence: true

  scope :search, -> (search) { 
    where('users.first_name ILIKE ?', "%#{search}%").or(where('users.last_name ILIKE ?', "%#{search}%"))
                                                    .or(where('users.email ILIKE ?', "%#{search}%"))
  }

  enum gender: {
    Female: 0,
    Male: 1,
    Other: 2
  }

  def name
    "#{first_name} #{last_name}"
  end

  def parent_name
    "#{parent_first_name} #{parent_last_name}"
  end

  def volunteer
    gender.eql?('Female') ? 'Sevadarni' : 'Sevadar'
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < AdminController
  load_resource :region

  before_action :load_user, except: [:index]
  
  def index
    @pagy, @users = if @region
      pagy(@region.users.distinct.order(sort_by_multiple_columns))
    else
      pagy(User.search(params[:search]).order(sort_by_multiple_columns))
    end
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user.update(user_params)
    bypass_sign_in @user, scope: :user
    redirect_to admin_users_path
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit!
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :load_user
  
  def show
    user = User.find(params[:id])
    decimal_time = user.volunteer_hours.pluck(:time_worked).reduce(:+) || 0
    @hours_volunteered = decimal_to_hours_and_minutes(decimal_time)
    @admin_user = user.admin?
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user.update(user_params)
    bypass_sign_in @user, scope: :user
    redirect_to admin_users_path
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit!
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/_form.html.erb
<div class="grid-x">
	<div class="cell large-6 medium-6">
		<%= simple_form_for [:admin, @user] do |f| %>
			<div class="grid-x grid-margin-x">
				<div class="cell large-6 medium-6">
					<%= f.input :first_name, autofocus: true, placeholder: "First name", required: '' %>
				</div>
				<div class="cell large-6 medium-6">
					<%= f.input :last_name, placeholder: "Last name", required: '' %>
				</div>
			</div>
			<div class="row">
				<%= f.email_field :email, placeholder: "Email", required: '' %>
			</div>
			<div class="row">
				<%= f.password_field :password, autocomplete: "off", placeholder: "Password", required: '' %>
			</div>
			<div class="row">
				<%= f.label :birthday %>
				<div class="birthday-wrapper">
					<%= f.input :birthday, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12, :order => [:month, :day, :year], default: {year: '1995'}, label: false %>
				</div>
			</div>
			<div class="row">
				<%= f.input :address, placeholder: "address", required: '' %>
			</div>
			<div class="grid-x grid-margin-x">
				<div class="cell large-4 medium-4">
					<%= f.input :city, label: 'city', required: '' %>
				</div>
				<div class="cell large-4 medium-4">
					<%= f.input :state, label: 'state', as: :select, collection: us_states, required: '' %>
				</div>
				<div class="cell large-4 medium-4">
					<%= f.input :zip_code, required: '' %>
				</div>
			</div>
			<div class="row">
				<%= f.input :gender, as: :select, collection: User.genders.keys, label: 'Gender', required: '' %>
			</div>
			<div class="row">
				<%= f.input :phone, label: 'phone', required: '' %>
			</div>
			<div class="grid-x grid-margin-x">
				<div class="cell large-6 medium-6">
					<%= f.input :parent_first_name, required: '' %>
				</div>
				<div class="cell large-6 medium-6">
					<%= f.input :parent_last_name, required: '' %>
				</div>
			</div>
			<div class="row">
				<%= f.input :parent_email, required: '' %>
			</div>
			<div class="row">
				<%= f.input :parent_phone, required: '' %>
			</div>
			<div class="row">
				<%= f.input :school_year, as: :select, collection: school_years, required: '' %>
			</div>
			<div class="row">
				<%= f.submit 'Save', class: 'button' %>
				<%= link_to 'Cancel', admin_users_path, class: 'button', style: 'margin-left:0.5rem;' %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/users/_search_form.html.erb
<%= form_tag admin_users_path, method: :get, id: 'search-users' do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
	<div class="grid-x grid-margin-x">
		<div class="cell large-5 medium-5 small-8">
			<%= text_field_tag :search, params[:search], placeholder: 'Search volunteers by name or email' %>
		</div>
		<div class="cell auto">
			<%= submit_tag 'Search', name: nil, class: 'button search-button' %>
		</div>
	</div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="admin-page admin-users-page" id="edit-volunteer">
	<h1 class="text-center">Edit Volunteer</h1>
	<%= render partial: 'form' %>
</div>

app/views/admin/users/index.html.erb
<div class="admin-page admin-users-page">
  <h1 class="text-center">Volunteers</h1>
  <% if @users.any? %>
    <%= render partial: 'search_form' %>
    <div class="table-scroll">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>
              <%= sortable('users.first_name, users.last_name','Name') %>
            </th>
            <th>
              <%= sortable('email') %>
            </th>
            <th>Phone #</th>
            <th>
              <%= sortable('admin') %>
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |volunteer| %>
            <tr>
              <td>
                <%= volunteer.id %>
              </td>
              <td>
                <%= link_to volunteer.name, user_path(volunteer) %>
              </td>
              <td>
                <%= volunteer.email %>
              </td>
              <td id="phone-num">
                <%= format_phone_num(volunteer.phone) %>
              </td>
              <td>
                <%= volunteer.admin? %>
              </td>
              <td>
                <% if current_user.eql?(volunteer) %>
                  <%= link_to 'Edit', edit_admin_user_path(volunteer) %>
                  |
                  <%= link_to 'Delete', admin_user_path(volunteer), class: 'delete-action', data: { confirm: 'Are you sure?', method: :delete } %>
                <% else %>
                  <%= link_to 'Delete', admin_user_path(volunteer), class: 'delete-action', data: { confirm: 'Are you sure?', method: :delete } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <div class="pagination-wrapper admin">
    <div class="pagination-info">
      <%= pagy_info(@pagy).html_safe %>
    </div>
    <%= pagy_foundation_nav(@pagy).html_safe if @pagy.pages > 1 %>
  </div>
</div>